apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chp04-set434-role
  namespace: chp04-set434
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames: ["privileged"] # psp name

- apiGroups: [""]
  resources: ["pods", "replicaset"]
  verbs: ["get", "list", "watch", "create", "apply"]

