apiVersion: v1
kind: Service
metadata:
  name: kubia-loadbalancer
  namespace: chp05-set532
spec:
  type: LoadBalancer # not Nodeport
  ports:
  - port: 80
    targetPort: 8080
    # we let Kubernetes choose the specific node port
  selector:
    app: kubia

