apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: chp05-set561
spec:
  replicas: 3
  selector:
    app: kubia

#    matchExpressions:
#    - key: app
#      operator: In
#      values:
#      - kubia

  # pod template for creating new pods
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
          initialDelaySeconds: 3 # default is 0
          periodSeconds: 5 # default is 10
