apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenantconfigs.thns.com
spec:
  group: thns.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantId:
                  type: string
                  pattern: '^\d{0,5}$' # up to 5 integers
                category:
                  type: string
                  default: "Category A"
                isCanaryCustomer:
                  type: boolean
                  default: false
  scope: Cluster
  names:
    plural: tenantconfigs
    singular: tenantconfig
    kind: TenantConfig
    shortNames:
    - tc


