apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: chp13-set1335
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: true
