apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
  name: psp-privileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['privileged']
