apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v2
  namespace: chp09-set921
spec:
  replicas: 1
  template: # pod template
    metadata:
      name: kubia
      labels: # need this pod label to be selected by the service
        app: kubia
    spec:
      # Create a ReplicationController for pods running this image
      containers: 
      - image: georgebaptista/kubia:v2
        name: nodejs
