apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: chp12-set1224
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      containers:
      - image: luksa/kubectl-proxy
        name: kubia 
