apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: chp03-set322
  labels:
    creation_method: manual
spec:
  containers:
  - image: georgebaptista/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
