apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  namespace: chp03-set322
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: georgebaptista/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP

