apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
  namespace: chp14-set1452
spec:
  hard:
    requests.storage: 2Gi # limit of overall claimable storage
    ssd.storageclass.storage.k8s.io/requests.storage: 100Mi # specific to ssd
    fast.storageclass.storage.k8s.io/requests.storage: 10Mi # specific to fast
