apiVersion: v1
kind: Pod
metadata:
  name: pod-as-user-guest
  namespace: chp13-set1332
#  namespace: default
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 405

