apiVersion: v1
kind: Pod
metadata:
  name: curl-restrictive
  namespace: chp15-set1512
spec:
  tolerations:
  - key: node-type
    operator: Equal
    value: non-production
    effect: NoSchedule
  serviceAccountName: foo
  containers:
  - name: curl-restrictive
    image: luksa/kubectl-proxy
    securityContext:
      privileged: false
      runAsUser: 2222

