apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia # no need to include app version name
  namespace: chp11-set1112
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia # match spec.template.metadata.labels
  template:
    metadata:
      name: kubia
      labels:
        app: kubia # match spec.selector.matchLabels
    spec:
      containers:
      - image: georgebaptista/kubia:v1
        name: nodejs

# The basic layout is very similar to a ReplicationController.
