apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
  namespace: chp12-set1214
spec:
  serviceAccountName: foo # use foo instead of default
  containers:
  - name: main
    image: georgebaptista/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: georgebaptista/kubectl-proxy

