apiVersion: v1
kind: Pod
metadata:
  name: curl-restrictive
  namespace: chp14-set1453
spec:
  serviceAccountName: foo
  containers:
  - name: curl-restrictive
    image: luksa/kubectl-proxy
    securityContext:
      privileged: false
      runAsUser: 2222

