apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
  namespace: chp14-set1451
spec:
  hard:
    requests.cpu: 400m
    requests.memory: 200Mi
    limits.cpu: 600m
    limits.memory: 500Mi

