apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: my-role
  namespace: chp12-set1227
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
