apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: kubia
      namespace: chp15-set151
    spec:
      clusterIP: 10.152.183.212
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app: kubia
      sessionAffinity: None
      type: ClusterIP
kind: List
