apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubia
  namespace: chp15-set151
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      namespace: chp15-set151
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
