apiVersion: v1
kind: ReplicationController
metadata:
  name: foo
  namespace: chp05-set541
spec:
  replicas: 3
  selector:
    app: foo
  template:
    metadata:
      labels:
        app: foo 
    spec:
      containers:
      - name: foo 
        image: luksa/kubia
        ports:
        - containerPort: 8080
