apiVersion: v1
kind: ReplicationController
metadata:
  name: bar
  namespace: chp05-set541
spec:
  replicas: 3
  selector:
    app: bar 
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar 
        image: luksa/kubia
        ports:
        - containerPort: 8080
