apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "example.com:website:crd-reader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "example.com:website:reader"
subjects:
- kind: ServiceAccount
  name: crd-reader
  namespace: chp18-set1811b
  
