apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.extensions.example.com # fullname
spec:
  versions: 
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              gitRepo:
                type: string
  scope: Namespaced
  group: extensions.example.com # group name, used for apiVersion, apiGroups
  names:
    kind: Website
    singular: website
    plural: websites
    shortNames:
    - web

