apiVersion: v1
kind: Service
metadata:
  name: fortune
  namespace: chp17-set1723
spec:
  selector:
    app: fortune-server
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-server
  namespace: chp17-set1723
  labels:
    app: fortune-server
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - image: luksa/fortune:args
    args: ["2"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
