apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  namespace: chp02-set231-declarative
  labels:
    version: "1"
    app: kubia
    env: dev
  annotations:
    omame.com/owner: "George Baptista"
spec:
  replicas: 3
  selector:
    run: kubia # used by service
  template:
    metadata:
      labels:
        run: kubia
    spec:
      # to be super explicit
      serviceAccountName: default
      containers:
      - name: kubia
        image: georgebaptista/kubia:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 2 
          failureThreshold: 3
