apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: chp05-set544
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        #image: georgebaptista/kubia
        ports:
        - containerPort: 8080
