apiVersion: v1
kind: Pod
metadata:
  name: pod-with-termination-message
  namespace: chp17-set179
spec:
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - 'echo "***** I''ve had enough" > /var/termination-reason ; sleep 10; exit 1'
    terminationMessagePath: /var/termination-reason
