apiVersion: v1
kind: Pod
metadata:
  name: pod-with-prestop-hook
  namespace: chp17-set176
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    # hook executes immediately before a container is terminated 
    lifecycle:
      preStop:
        # request is sent to http://POD_IP:8080/shutdown
        httpGet:
          port: 8080
          path: shutdown
