apiVersion: v1
kind: Service
metadata:
  labels:
    webserver: baptista-website
  name: baptista-website
  namespace: chp18-set1812
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30007
  selector:
    webserver: baptista-website
