apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: chp05-set531
spec:
  replicas: 9
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
