apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo

# This is another cluster-level RBAC resource.
# ClusterRoleBinding is used to grant access to cluster-level resources.
# In general, you will use the combination of ClusterRole and ClusterRoleBinding when granting access to cluster-level resources.

# imperative style:
# kubectl create clusterrolebinding pv-test --clusterrole=pv-reader --serviceaccount=foo:default
