apiVersion: v1
kind: Pod
metadata:
  name: pod-with-prestop-hook
  namespace: chp17-set177
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    lifecycle:
      preStop:
        exec:
          command:
          - sh
          - c
          - "echo 'hook will fail with exit code 15'; exit 15"
