apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job
  namespace: chp04-set454
spec:
  completions: 5 # make this Job run 5 pods sequentially
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: georgebaptista/batch-job
