apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: chp05-set552
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          exec:
            command:
            - ls
            - /var/ready
