apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
  namespace: chp07-set722
  labels:
    app: fortune2s
    env: dev
    ver: "1"
spec:
  volumes:
  - name: html 
    emptyDir: {}
  containers:
  - image: georgebaptista/fortune:args
    args: ["2"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP

