apiVersion: v1
kind: Service
metadata:
  name: website-controller
  namespace: chp18-set1812
spec:
  ports:
  - port: 80
    #targetPort: 8080
  selector:
    # we are exposing deployment.apps/website-controller
    app: website-controller
