apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia # no need to include app version name
  namespace: chp09-set935
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia # match spec.template.metadata.labels
  template:
    metadata:
      name: kubia
      labels:
        app: kubia # match spec.selector.matchLabels
        app.kubernetes.io/version: "3.0"
        #version: "3"
    spec:
      containers:
#      - image: georgebaptista/kubia:v1 # ok release
      - image: georgebaptista/kubia:v3 # bad release
        name: nodejs
