apiVersion: v1
kind: Pod
metadata:
  name: kubia
  namespace: chp05-set522
  labels:
    app: kubia
    env: prod
    ver: "1"
  annotations:
    mycompany.com/someannotation: This is an annotation
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
