apiVersion: v1
kind: Endpoints
metadata:
  name: external-service # match name of service
  namespace: chp05-set522
subsets:
- addresses:
  # endpoint IPs that the service will forward connections to
  - ip: 11.11.11.11
  - ip: 22.22.22.22
  ports:
  - port: 80 # target port of endpoints

# Endpoints are a separate resource and not an attribute of a service.
# When we create services with selectors, the corresponding Endpoints
# resources are created automatically.
# However, here we created services w/o selectors, hence we have to create
# the Endpoints here manually.

