apiVersion: v1 
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: test
    namespace: foo
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: service-reader

  subjects:
  - kind: ServiceAccount # User, Group
    name: default
    namespace: foo

  - kind: ServiceAccount
    name: default
    namespace: bar
