apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
  namespace: chp08-set823
spec:
  containers:
  - name: main
    #image: tutum/curl
    image: georgebaptista/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    #image: luksa/kubectl-proxy:1.8.0
    image: georgebaptista/kubectl-proxy
    imagePullPolicy: Always

