apiVersion: batch/v1
kind: Job
metadata:
  namespace: chp04-set455
  name: multi-completion-batch-job
spec:
  completions: 5 # ensure 5 pods complete successfully
  parallelism: 3 # up to 3 pods can run in parallel
  template: 
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: georgebaptista/batch-job 
