apiVersion: v1
kind: Pod
metadata:
  name: pod-with-poststart-hook
  namespace: chp17-set1724
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    # postStart hook executes as soon as container starts
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "echo 'container started, now hook will fail with exit code'; sleep 5; exit 15"
    terminationMessagePath: /var/termination-reason
    command:
    - sh
    - -c
    - 'echo "I had enough" > /var/termination-reason ; exit 1'

