apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonly-filesystem
  namespace: chp13-set1326
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    # GB - if we are using PodSecurityPolicy, maybe we really don't need pod-level securityContext?
    securityContext:
      # this container's filesystem cannot be written to
      readOnlyRootFilesystem: true
    volumeMounts:
      # writing to /volume is allowed, because a volume is mounted there
    - name: my-volume
      mountPath: /volume
      readOnly: false
  volumes:
  - name: my-volume
    emptyDir:
