apiVersion: v1 
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: test
    namespace: foo
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    # This RoleBinding references the service-reader Role
    kind: Role
    name: service-reader
  subjects:
    # and binds it to the default ServiceAccount in the foo namespace
  - kind: ServiceAccount # User, Group
    name: default
    namespace: foo

  - kind: ServiceAccount
    name: default
    namespace: bar
