apiVersion: v1
kind: Pod
metadata:
  name: pod-nonprivileged
  namespace: chp13-set1331
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: false
