apiVersion: extensions.example.com/v1
kind: Website
metadata:
  name: kubia
  namespace: chp18-set1812
spec:
  gitRepo: https://github.com/luksa/kubia-website-example.git
#  securityContext:
#    runAsNonRoot: true
#    runAsUser: 1000
