apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-psp

subjects:
- kind: ServiceAccount
  name: website-controller
  namespace: chp18-set1812

#- kind: ServiceAccount
#  name: default
#  namespace: chp18-set1812

#- apiGroup: rbac.authorization.k8s.io # OK
#  kind: Group
#  name: system:serviceaccounts:chp18-set1812
