apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-psp
  labels:
    type: clusterrole
rules:
- apiGroups: ["extensions.example.com"]
  resources: ["websites"]
  verbs: ["*"]

- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create"]

- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["policy"]
  resourceNames: ["restricted"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]

