apiVersion: v1
kind: Pod
metadata:
  name: curl-privileged
  namespace: chp14-set1454
spec:
  serviceAccountName: foo
  containers:
  - name: curl-privileged
    image: georgebaptista/curl
    command: ["sleep", "9999999"]
    securityContext:
      runAsUser: 1111 
  - name: ambassador
    image: georgebaptista/kubectl-proxy
    securityContext:
      privileged: true
      runAsUser: 2222

